---
- name: Install Docker via get.docker.com
  hosts: debian
  become: true
  gather_facts: false

  vars:
    docker_install_script_url: "https://get.docker.com"

  tasks:
    - name: Download install script
      ansible.builtin.get_url:
        url: "{{ docker_install_script_url }}"
        dest: "/tmp/get-docker.sh"
        mode: "0755"

    - name: Run install script
      ansible.builtin.command: "sh /tmp/get-docker.sh"
      args:
        creates: /usr/bin/docker

    - name: Remove install script
      ansible.builtin.file:
        path: "/tmp/get-docker.sh"
        state: absent

    - name: Start and enable docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Verify docker is running
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false

    - name: Show docker version
      ansible.builtin.debug:
        msg: "{{ docker_version.stdout }}"
